flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # 1. Permitir todo lo interno (necesario para dbus y apps locales)
        iif "lo" accept

        # 2. Mantener conexiones que TÚ iniciaste (Navegar, descargar repo de Git)
        ct state established,related accept

        # 3. ICMP (Para diagnóstico de red)
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        # 4. Puertos para desarrollo (Solo accesibles desde tu laptop)
        iifname "lo" tcp dport { 8000, 8080, 5000, 3000 } accept

        # 5. LocalSend (Transferencia de archivos) - Abierto para cualquier interfaz
        tcp dport 53317 accept
        udp dport 53317 accept

        # 6. mDNS y Descubrimiento (Para que LocalSend y la Impresora te encuentren)
        udp dport 5353 accept

        # 7. Servicios de impresión (CUPS / IPP) - Abierto para cualquier interfaz
        tcp dport 631 accept
        udp dport 631 accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}
