# --- Configuración Kitty para vpul ---

# Fuente (Ya que instalamos JetBrains Mono)
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Ventana y Estética
window_padding_width 10
background_opacity 0.92
background #2e3440
foreground #d8dee9

# Protocolo de Imágenes (Vital para Yazi)
# Kitty lo maneja nativamente, pero aquí optimizamos el rendimiento
allow_remote_control yes
listen_on unix:/tmp/mykitty

# Pestañas (Lo que buscabas)
tab_bar_style powerline
active_tab_foreground   #2e3440
active_tab_background   #88c0d0
inactive_tab_foreground #d8dee9
inactive_tab_background #3b4252

# Desactivar el sonido de campana (por salud mental en los laboratorios)
enable_audio_bell no

shell /usr/bin/nu
